id: 4944d575-a819-4af5-8acc-e1d183b0170f
version: 57
vcShouldKeepItemLegacyProdMachine: false
name: OTML - Phishing URL Handling - Main playbook
tags:
- prod
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c8c0a155-76eb-4960-8d75-4a07731866d4
    type: start
    task:
      id: c8c0a155-76eb-4960-8d75-4a07731866d4
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 65
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: fbca310d-46bd-4b24-8b15-b1741742b51a
    type: regular
    task:
      id: fbca310d-46bd-4b24-8b15-b1741742b51a
      version: -1
      name: Get email information from Mimecast
      description: |-
        Execute an XQL query and retrieve results of an executed XQL query API. The command will be executed every 10 seconds until results are retrieved or until a timeout error is raised.
        When more than 1000 results are retrieved, the command will return a compressed gzipped JSON format file,
        unless the argument 'parse_result_file_to_context' is set to true and then the results will be extracted to the context.
      script: '|||xdr-xql-generic-query'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      query:
        simple: "dataset = mimecast_mimecast_raw \n| filter xsiem_classifier contains
          \"siem\" | filter url = \"${alert.detectionurl}\"\n| fields MsgId, Sender
          , Subject, url, urlCategory , Action , SenderDomain , SourceIP , reason
          \n| join (dataset = mimecast_mimecast_raw | filter xsiem_classifier contains
          \"siem\" | filter rcpt != null and Act != null | fields MsgId , Rcpt , IP,
          Dir, Act ) as rcpt_info MsgId = rcpt_info.MsgId"
      query_name:
        simple: Search Mimecast for matched URL
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1625
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: c89b791c-7a39-4a39-8fec-5cafb02f730a
    type: playbook
    task:
      id: c89b791c-7a39-4a39-8fec-5cafb02f730a
      version: -1
      name: OTML - Process Phishing Email
      playbookName: OTML - Process Phishing Email
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "36"
    scriptarguments:
      message:
        simple: ${PaloAltoNetworksXQL.GenericQuery.results}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 5
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1975
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: c5b070af-9c82-4711-8c1b-8411936034c1
    type: regular
    task:
      id: c5b070af-9c82-4711-8c1b-8411936034c1
      version: -1
      name: Close alert
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 2325
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 0df4cea5-8e5e-475b-8e2d-28784d4c5cb6
    type: playbook
    task:
      id: 0df4cea5-8e5e-475b-8e2d-28784d4c5cb6
      version: -1
      name: URL Enrichment - Generic v2
      description: |-
        Enrich URLs using one or more integrations.

        URL enrichment includes:
        * SSL verification for URLs.
        * Threat information.
        * Providing of URL screenshots.
        * URL Reputation using !url.
      playbookName: URL Enrichment - Generic v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "32"
    scriptarguments:
      Rasterize:
        simple: "True"
      URL:
        complex:
          root: alert
          accessor: detectionurl
          transformers:
          - operator: uniq
      UseReputationCommand:
        simple: "True"
      VerifyURL:
        simple: "False"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 925
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: 04e32af4-e874-491d-87e9-85d5b76037b6
    type: condition
    task:
      id: 04e32af4-e874-491d-87e9-85d5b76037b6
      version: -1
      name: Found in Mimecast?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "36"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PaloAltoNetworksXQL.GenericQuery.results
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: 5f51723d-d5c9-4267-81c2-57729ffffbdb
    type: regular
    task:
      id: 5f51723d-d5c9-4267-81c2-57729ffffbdb
      version: -1
      name: Delete Context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: 532173ff-30e8-4077-8bef-00eb9413de06
    type: condition
    task:
      id: 532173ff-30e8-4077-8bef-00eb9413de06
      version: -1
      name: Check detection URL
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "29"
      "yes":
      - "31"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: alert.detectionurl
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "28":
    id: "28"
    taskid: 91603662-d885-4322-8862-435f3699271d
    type: regular
    task:
      id: 91603662-d885-4322-8862-435f3699271d
      version: -1
      name: Set Detection URL
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      detectionurl:
        complex:
          root: alert
          accessor: uri
          transformers:
          - operator: RegexExtractAll
            args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: '[^\"\''\[\],]+'
              unpack_matches: {}
          - operator: FirstArrayElement
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "29":
    id: "29"
    taskid: a354387b-eb66-4402-8b38-365226ed21fc
    type: condition
    task:
      id: a354387b-eb66-4402-8b38-365226ed21fc
      version: -1
      name: Get URL
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "23"
      uri:
      - "28"
      url:
      - "30"
    separatecontext: false
    conditions:
    - label: uri
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: alert.uri
            iscontext: true
          right:
            value: {}
    - label: url
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: alert.url
            iscontext: true
    - label: detectionurl
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: alert.detectionurl
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 575
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "30":
    id: "30"
    taskid: 0452032e-cd21-4a98-8ffa-f99f9164e244
    type: regular
    task:
      id: 0452032e-cd21-4a98-8ffa-f99f9164e244
      version: -1
      name: Set Detection URL
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      detectionurl:
        complex:
          root: alert
          accessor: url
          transformers:
          - operator: RegexExtractAll
            args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: '[^\"\''\[\],]+'
              unpack_matches: {}
          - operator: FirstArrayElement
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 500,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "31":
    id: "31"
    taskid: 0853e66e-1bff-4602-8a2e-74649b00f61a
    type: regular
    task:
      id: 0853e66e-1bff-4602-8a2e-74649b00f61a
      version: -1
      name: Set Detection URL
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      detectionurl:
        complex:
          root: alert
          accessor: detectionurl
          transformers:
          - operator: RegexExtractAll
            args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: '[^\"\''\[\],]+'
              unpack_matches: {}
          - operator: FirstArrayElement
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 930,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "32":
    id: "32"
    taskid: fc5631f7-e679-4936-8b66-902936a3da2c
    type: regular
    task:
      id: fc5631f7-e679-4936-8b66-902936a3da2c
      version: -1
      name: Extract Domain
      description: commands.local.cmd.extract.indicators
      script: Builtin|||extractIndicators
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "34"
    scriptarguments:
      text:
        simple: ${alert.detectionurl}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "33":
    id: "33"
    taskid: fcc80cd0-3fe1-4d3c-80f6-0747b3fd9830
    type: playbook
    task:
      id: fcc80cd0-3fe1-4d3c-80f6-0747b3fd9830
      version: -1
      name: TIM - Process Domains With Whois
      description: This playbook uses several sub playbooks to process and tag indicators
        based on the results of the Whois tool.
      playbookName: TIM - Process Domains With Whois
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      CheckForWhoisDomainAgeCreation:
        simple: "True"
      CheckForWhoisRegistrant:
        simple: "True"
      indicator_type:
        simple: Domain
      indicator_value:
        simple: ${ExtractedIndicators.Domain.[0]}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "34":
    id: "34"
    taskid: 0db5c519-d511-4719-84c4-5b0ee11ff15f
    type: condition
    task:
      id: 0db5c519-d511-4719-84c4-5b0ee11ff15f
      version: -1
      name: Domain found
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "33"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ExtractedIndicators.Domain
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1275
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "35":
    id: "35"
    taskid: 37dd579e-b03e-454d-8a2d-98063efe36f8
    type: regular
    task:
      id: 37dd579e-b03e-454d-8a2d-98063efe36f8
      version: -1
      name: Set Detection URL
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      detectionurl:
        simple: https://testdata.com
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1032.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "36":
    id: "36"
    taskid: 128d6abb-696c-432e-85fc-40a10eb1ec8b
    type: playbook
    task:
      id: 128d6abb-696c-432e-85fc-40a10eb1ec8b
      version: -1
      name: OTML - Close Jira Ticket
      playbookName: OTML - Close Jira Ticket
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 2150
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2370,
        "width": 1362.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
