id: 307e3702-6f78-4152-8ec6-6ec2bae6747b
version: 35
vcShouldKeepItemLegacyProdMachine: false
name: OTML - O365 Add App role assignment grant user
tags:
- prod
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d9d6ca42-3724-448e-8a1a-1acfd20791ea
    type: start
    task:
      id: d9d6ca42-3724-448e-8a1a-1acfd20791ea
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 52983e4c-9bd1-461d-84c3-76e6eb65f4f6
    type: regular
    task:
      id: 52983e4c-9bd1-461d-84c3-76e6eb65f4f6
      version: -1
      name: Get user information
      description: |-
        Retrieves the properties and relationships of a user object. For more information, visit: https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0).
        Permissions: - User.Read (Delegated) - User.Read.All (Application).
      script: '|||msgraph-user-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      user:
        simple: ${alert.userid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 2086297b-e2c5-4dfe-811c-e6c5d2628857
    type: condition
    task:
      id: 2086297b-e2c5-4dfe-811c-e6c5d2628857
      version: -1
      name: Manual application check
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Application is Suspicious:
      - "20"
      Application is legitimate:
      - "21"
    separatecontext: false
    slareminder:
      minutes: 15
      hours: 0
      days: 0
      weeks: 0
    defaultassigneecomplex:
      simple: ${alert.assigneduser}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1915
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 554eea9a-3745-449e-8730-a8e4f3668a71
    type: regular
    task:
      id: 554eea9a-3745-449e-8730-a8e4f3668a71
      version: -1
      name: Search User Login History
      description: |-
        Execute an XQL query and retrieve results of an executed XQL query API. The command will be executed every 10 seconds until results are retrieved or until a timeout error is raised.
        When more than 1000 results are retrieved, the command will return a compressed gzipped JSON format file,
        unless the argument 'parse_result_file_to_context' is set to true and then the results will be extracted to the context.
      script: Cortex XDR - XQL Query Engine_XSIAM|||xdr-xql-generic-query
      type: regular
      iscommand: true
      brand: Cortex XDR - XQL Query Engine_XSIAM
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      query:
        simple: "config timeframe = 24h\n| dataset = msft_azure_ad_raw \n| filter
          UserId = \"${inputs.user}\"\n| filter isInteractive = 1\n| alter errorCode
          = json_extract_scalar(status, \"$.errorCode\")\n| alter failureReason =
          json_extract_scalar(status, \"$.failureReason\")\n| alter additionalDetals
          = json_extract_scalar(status, \"$.additionalDetails\")\n| filter errorCode
          NOt in (\"50074\" ,\"50076\", \"50097\" )\n| comp count(if(errorCode = \"0\",
          true)) as Successes, count(if(errorCode != \"0\", true)) as failures, values(failureReason)"
      query_name:
        simple: User Login History
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 738e7b92-8656-447b-8a5b-a791e18bc0b7
    type: regular
    task:
      id: 738e7b92-8656-447b-8a5b-a791e18bc0b7
      version: -1
      name: Close
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 490,
          "y": 2440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: f55863e6-8275-4883-83af-71c649748a2d
    type: playbook
    task:
      id: f55863e6-8275-4883-83af-71c649748a2d
      version: -1
      name: OTML - Close Jira Ticket
      playbookName: OTML - Close Jira Ticket
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 2265
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 8e539d04-e342-4fcb-84a8-4e01dfa0943a
    type: regular
    task:
      id: 8e539d04-e342-4fcb-84a8-4e01dfa0943a
      version: -1
      name: HTTP Get From Github app list
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      method:
        simple: GET
      url:
        simple: https://raw.githubusercontent.com/merill/microsoft-info/main/_info/MicrosoftApps.json
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: f6984e7e-fc35-498d-8e3c-69e03efe2447
    type: condition
    task:
      id: f6984e7e-fc35-498d-8e3c-69e03efe2447
      version: -1
      name: Check application ID
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "25"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: JsonObject
            iscontext: true
          right:
            value:
              simple: alert.app
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 1c9b004c-5f6c-40e8-8f78-27d03133da96
    type: regular
    task:
      id: 1c9b004c-5f6c-40e8-8f78-27d03133da96
      version: -1
      name: Parse JSON from HTTP Response body
      description: Loads a json from string input, and returns a json object result.
      scriptName: LoadJSON
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      input:
        simple: ${HttpRequest.Response.Body}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 3a48fb4f-e366-48c6-8cc7-188bf783048f
    type: regular
    task:
      id: 3a48fb4f-e366-48c6-8cc7-188bf783048f
      version: -1
      name: Raise with Client - Engage and Teams
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 725,
          "y": 2265
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: fc799a78-33e1-4fa9-84ca-c10b626234f5
    type: regular
    task:
      id: fc799a78-33e1-4fa9-84ca-c10b626234f5
      version: -1
      name: Create Exclusion
      description: commands.local.cmd.new.indicator
      script: Builtin|||createNewIndicator
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      tags:
        simple: Playbook allowlisting addition
      type:
        simple: Azure Application
      value:
        simple: ${alert.app}
      verdict:
        simple: Benign
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: 09726cc5-a3f5-47bf-8180-f4f3bc8e5405
    type: regular
    task:
      id: 09726cc5-a3f5-47bf-8180-f4f3bc8e5405
      version: -1
      name: Check Indicator Allowlist
      description: commands.local.cmd.find.indicators
      script: Builtin|||findIndicators
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      value:
        simple: ${alert.app}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 45ea1d46-b1c6-4846-8163-ccc423f50ba7
    type: regular
    task:
      id: 45ea1d46-b1c6-4846-8163-ccc423f50ba7
      version: -1
      name: Check If App is in Indicators Allowlist
      description: Add into the incident's context the system internal DBot score
        for the input indicator.
      scriptName: GetIndicatorDBotScore
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      indicator:
        simple: ${alert.app}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: d47bb872-691e-42e6-8478-59a85448267b
    type: condition
    task:
      id: d47bb872-691e-42e6-8478-59a85448267b
      version: -1
      name: Is App Benign?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              simple: DBotScore.Score
            iscontext: true
          right:
            value:
              simple: "1"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: 07091f1f-6073-4293-83ef-62be61e61edc
    type: regular
    task:
      id: 07091f1f-6073-4293-83ef-62be61e61edc
      version: -1
      name: Assign Task to Analyst
      description: |-
        Assign analyst to incident.
        Note: the script should be executed from within an alert.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command.
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#error#':
      - "26"
      '#none#':
      - "6"
    scriptarguments:
      assignBy:
        simple: ${alert.assigneduser}
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: 3ddd0e3d-644e-4292-8385-a85507dc1e4f
    type: title
    task:
      id: 3ddd0e3d-644e-4292-8385-a85507dc1e4f
      version: -1
      name: No analyst assigned
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2485,
        "width": 1055,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: user
  value:
    simple: ${alert.username}
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - user
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
